//
//  ItineraryDocumentText.swift
//  Carry
//
//  签证行程单 PDF 的**文档内固定文案**（按所选语言渲染，与设备 locale 无关）。
//  导出二选一（EN / ZH），故用代码内小字典，不进 xcstrings（xcstrings 走设备 locale，
//  无法按选定语言取值）。用户数据（地点名/航司/酒店名）原样带出、不在此翻译。
//  spec: itinerary-export-document.md。
//

import Foundation

enum DocLanguage: String, CaseIterable, Identifiable {
    case en
    case zh        // 简体中文
    case zhHant    // 繁體中文（台 / 港 / 澳）
    var id: String { rawValue }

    /// 文档内日期/时间格式化用的 locale（与所选语言一致，跟设备无关）。
    var locale: Locale {
        switch self {
        case .en:     return Locale(identifier: "en_US")
        case .zh:     return Locale(identifier: "zh_Hans_CN")
        case .zhHant: return Locale(identifier: "zh_Hant_TW")
        }
    }

    /// 机场/航司多语言名（`nm`）的语言键：用于按**所选导出语言**取名（与设备语言无关）。
    /// `.en` → nil（回落英文原名）；`.zh` → 简体；`.zhHant` → 繁体（`nm` 的 `zh-Hant`）。
    var nameLanguageKey: String? {
        switch self {
        case .en:     return nil
        case .zh:     return "zh-Hans"
        case .zhHant: return "zh-Hant"
        }
    }

    /// 导出选项里给用户看的语言名（按其自身语言/字形写）。
    var displayName: String {
        switch self {
        case .en:     return "English"
        case .zh:     return "简体中文"
        case .zhHant: return "繁體中文"
        }
    }
}

/// 文档固定文案表。`L(.zh)` / `L(.en)` 取一份。
struct ItineraryDocumentText {
    let lang: DocLanguage

    /// 三语取一：英 / 简 / 繁。繁体未单独给（`zhHant == nil`）时回落简体——仅用于**繁简同字**的文案
    /// （如「日期」「目的地」「住宿」「入住」「退房」），字形一致、回落无误；繁简有别的（行程表 / 申請人 /
    /// 頁 / 產生…）必须显式给第三参（按台/港用语，非简转繁）。
    private func pick(_ en: String, _ zhHans: String, _ zhHant: String? = nil) -> String {
        switch lang {
        case .en:     return en
        case .zh:     return zhHans
        case .zhHant: return zhHant ?? zhHans
        }
    }

    var title: String       { pick("Travel Itinerary", "旅行行程单", "旅行行程表") }
    var applicant: String   { pick("Applicant", "申请人", "申請人") }
    var purpose: String     { pick("Purpose of visit", "出行目的", "旅行目的") }
    var dates: String       { pick("Dates", "日期") }
    var destination: String { pick("Destination", "目的地") }
    var accommodation: String { pick("Accommodation", "住宿") }
    var checkIn: String     { pick("Check-in", "入住") }
    var checkOut: String    { pick("Check-out", "退房") }
    var generatedBy: String { pick("Generated by Carry", "由 Carry 生成", "由 Carry 產生") }

    func dayTitle(_ n: Int) -> String { pick("Day \(n)", "第 \(n) 天") }
    func nights(_ n: Int) -> String   { pick(n == 1 ? "1 night" : "\(n) nights", "\(n) 晚") }
    func page(_ n: Int) -> String     { pick("Page \(n)", "第 \(n) 页", "第 \(n) 頁") }

    /// 「周几 月/日」标题日期（如 Fri, Jun 19 / 6月19日 周五），按所选语言。
    func dayDate(_ date: Date) -> String {
        date.formatted(.dateTime.weekday(.abbreviated).month(.abbreviated).day().locale(lang.locale))
    }

    /// 起止日期区间（如 Jun 19 – Jun 21）。
    func dateRange(from: Date, to: Date) -> String {
        let f = from.formatted(.dateTime.month(.abbreviated).day().locale(lang.locale))
        let t = to.formatted(.dateTime.month(.abbreviated).day().locale(lang.locale))
        return "\(f) – \(t)"
    }

    /// 时间（随所选语言 12/24 制）。
    func time(minutes: Int) -> String {
        let start = Calendar.current.startOfDay(for: Date())
        let date = Calendar.current.date(byAdding: .minute, value: max(0, minutes), to: start) ?? start
        return date.formatted(.dateTime.hour().minute().locale(lang.locale))
    }

    /// 文档内交通方式名（按所选语言，不取设备 locale）。繁体仅 火車 / 渡輪 / 自駕 异于简体。
    func modeName(_ m: TransportMode) -> String {
        switch m {
        case .flight:    return pick("Flight", "航班")
        case .train:     return pick("Train", "火车", "火車")
        case .bus:       return pick("Bus", "巴士")
        case .ferry:     return pick("Ferry", "渡轮", "渡輪")
        case .carRental: return pick("Car", "自驾", "自駕")
        case .other:     return pick("Transport", "交通")
        }
    }
}
