//
//  SurpriseItemMap.swift
//  Carry
//

import Foundation

// MARK: - SurpriseItem

struct SurpriseItem: Identifiable {
    var id: String { name }
    let name: String
    let note: String
    let category: ItemCategory
}

// MARK: - Scene → surprise item map

let surpriseItemMap: [String: [SurpriseItem]] = [
    "road_trip": [
        SurpriseItem(name: "Car phone mount",
                     note: "Hands-free navigation is the law in most places — and your co-pilot won't always be awake",
                     category: .essentials),
        SurpriseItem(name: "Jump starter / jump leads",
                     note: "A flat battery on a remote road is a genuine emergency, not just an inconvenience",
                     category: .essentials),
        SurpriseItem(name: "Window sunshade",
                     note: "Parked in the sun, your steering wheel becomes untouchable — costs almost nothing to prevent",
                     category: .essentials),
        SurpriseItem(name: "Offline maps downloaded",
                     note: "Mobile signal disappears exactly when you need navigation most — download before you leave",
                     category: .essentials),
        SurpriseItem(name: "Wet wipes",
                     note: "Gas station stops, sticky snacks, impromptu cleanups",
                     category: .essentials),
        SurpriseItem(name: "Flat shoes",
                     note: "Driving in heels reduces pedal feel and reaction time — a pair of flats to swap into before getting behind the wheel is a small thing that makes a real difference on long stretches",
                     category: .clothing),
    ],
    "long_haul_flight": [
        SurpriseItem(name: "Empty water bottle",
                     note: "Fill after security — saves buying expensive airport water and keeps you hydrated mid-flight",
                     category: .essentials),
        SurpriseItem(name: "Noise-cancelling earphones",
                     note: "Even cheap ones transform a 12-hour flight — the engine drone wears you down without you realising",
                     category: .electronics),
        SurpriseItem(name: "Melatonin",
                     note: "Helps reset your body clock faster at the destination",
                     category: .health),
        SurpriseItem(name: "Flight snacks",
                     note: "Airline food timing rarely matches when you're actually hungry",
                     category: .essentials),
        SurpriseItem(name: "Change of clothes in carry-on",
                     note: "Luggage gets lost more than you'd think — having tomorrow's outfit on you is genuine insurance",
                     category: .clothing),
    ],
    "honeymoon": [
        SurpriseItem(name: "Portable speaker",
                     note: "Your own playlist beats hotel lobby music — and creates a reason to stay in",
                     category: .electronics),
        SurpriseItem(name: "Journey journal",
                     note: "Somewhere to write down the small details before they blur together into just 'the honeymoon'",
                     category: .essentials),
        SurpriseItem(name: "Nice perfume / cologne",
                     note: "You'll have more occasions to dress up than on a regular holiday",
                     category: .toiletries),
        SurpriseItem(name: "Massage oil",
                     note: "Small, travel-friendly, and creates its own atmosphere — worth the space",
                     category: .toiletries),
    ],
    "backpacking": [
        SurpriseItem(name: "Money belt",
                     note: "Keeps cash and cards against your body and out of reach when moving between cities",
                     category: .essentials),
        SurpriseItem(name: "Ziplock bags",
                     note: "Waterproofing documents, organising small items, separating wet clothes — endlessly useful",
                     category: .essentials),
        SurpriseItem(name: "Headlamp",
                     note: "Essential for hostel dorm access in the dark without waking eight strangers",
                     category: .essentials),
        SurpriseItem(name: "Portable door lock",
                     note: "Adds a layer of security in hostels and guesthouses where you can't always trust the lock",
                     category: .essentials),
    ],
    "city_break": [
        SurpriseItem(name: "Comfort insoles",
                     note: "City days can hit 20k+ steps — insoles can save your feet by day two",
                     category: .clothing),
        SurpriseItem(name: "Blister plasters",
                     note: "City walking destroys feet — have these before you need them, not after",
                     category: .health),
        SurpriseItem(name: "Collapsible tote bag",
                     note: "You will buy something at a market or deli — saves scrambling for a bag at the checkout",
                     category: .essentials),
        SurpriseItem(name: "Offline city map",
                     note: "Data drops at the worst moment — a downloaded map costs nothing and always works",
                     category: .essentials),
    ],
    "tropical": [
        SurpriseItem(name: "Oral rehydration salts",
                     note: "Heat + unfamiliar food can hit hard — these are a quiet lifesaver",
                     category: .health),
        SurpriseItem(name: "Antihistamine",
                     note: "Tropical plants, insect bites, unfamiliar foods — allergic reactions spike when everything is new",
                     category: .health),
        SurpriseItem(name: "Rash guard",
                     note: "Better sun protection than sunscreen alone, with no reapplying every 90 minutes",
                     category: .clothing),
        SurpriseItem(name: "Reef-safe sunscreen",
                     note: "Regular sunscreen damages coral reefs — worth switching in tropical waters",
                     category: .health),
        SurpriseItem(name: "Waterproof phone case",
                     note: "Snorkelling, pool edges, water taxis — peace of mind for everything around water",
                     category: .essentials),
    ],
    "winter": [
        SurpriseItem(name: "Hand warmers",
                     note: "Disposable heat packs — slip into gloves or pockets when it really bites",
                     category: .essentials),
        SurpriseItem(name: "Wool socks",
                     note: "Cotton socks in freezing temperatures become cold and damp fast — wool insulates even when wet",
                     category: .clothing),
        SurpriseItem(name: "Insulated water bottle",
                     note: "Keeps hot drinks genuinely hot for hours — changes your whole experience outdoors",
                     category: .essentials),
        SurpriseItem(name: "Vaseline / petroleum jelly",
                     note: "Apply to exposed skin before heading out — stops windburn instantly",
                     category: .toiletries),
        SurpriseItem(name: "Tissues / handkerchief",
                     note: "Cold air makes noses run constantly — running out of tissues in the cold is genuinely unpleasant",
                     category: .essentials),
    ],
    "hiking": [
        SurpriseItem(name: "Blister plasters",
                     note: "New boots + long trails = blisters — these prevent the worst",
                     category: .health),
        SurpriseItem(name: "Electrolyte tablets",
                     note: "Water alone doesn't replace what you sweat out on a long hike",
                     category: .health),
        SurpriseItem(name: "Emergency whistle",
                     note: "Three blasts is the universal distress signal — and it weighs almost nothing",
                     category: .essentials),
        SurpriseItem(name: "Waterproof dry bag",
                     note: "For when a stream crossing goes slightly wrong — protects everything that matters",
                     category: .essentials),
        SurpriseItem(name: "Duct tape (small roll)",
                     note: "Fixes a broken boot sole, a torn strap, or a blister spot — worth the 30g",
                     category: .essentials),
    ],
    "cruise": [
        SurpriseItem(name: "Magnetic hooks",
                     note: "Cruise cabin walls are magnetic — hang bags and coats with no damage",
                     category: .essentials),
        SurpriseItem(name: "Seasickness tablets",
                     note: "Wristbands help but when seas get rough, proper medication is what you'll actually want",
                     category: .health),
        SurpriseItem(name: "Power strip / multi-socket",
                     note: "Cruise cabins famously have very few sockets — one strip solves everyone's charging",
                     category: .electronics),
        SurpriseItem(name: "Portable fan",
                     note: "Cabins can get warm, especially in tropical ports — a small USB fan is a real sleep improvement",
                     category: .essentials),
    ],
    "business": [
        SurpriseItem(name: "Portable battery pack",
                     note: "Between airports, taxis, and dinners your phone will hit 3 percent at exactly the wrong moment",
                     category: .electronics),
        SurpriseItem(name: "Noise-cancelling earphones",
                     note: "Back-to-back flights, open lobbies, and conference calls — you'll use them constantly",
                     category: .electronics),
        SurpriseItem(name: "Compact umbrella",
                     note: "Arriving at a client's office soaked is not the impression you want to make",
                     category: .essentials),
        SurpriseItem(name: "Wrinkle-release spray",
                     note: "Meeting clothes out of a suitcase always need a refresh — no iron required",
                     category: .toiletries),
    ],
    "kids": [
        SurpriseItem(name: "Night light",
                     note: "New rooms are dark in unfamiliar ways — a simple plug-in night light prevents middle-of-the-night panic",
                     category: .essentials),
        SurpriseItem(name: "Children's pain/fever relief",
                     note: "Fever at 11pm in an unfamiliar country is when you want this to already be in your bag",
                     category: .health),
        SurpriseItem(name: "Extra outfit in carry-on",
                     note: "For spills at 30,000 feet — before you can access your checked luggage",
                     category: .clothing),
        SurpriseItem(name: "Familiar snacks from home",
                     note: "Picky eaters + unfamiliar food = avoidable stress — come prepared",
                     category: .essentials),
        SurpriseItem(name: "Sticker book or activity pad",
                     note: "For the unavoidable waiting — restaurants, airports, long car journeys",
                     category: .essentials),
    ],
    "high_altitude": [
        SurpriseItem(name: "Pulse oximeter",
                     note: "Small and cheap — monitoring blood oxygen shows how well you're actually acclimatising",
                     category: .health),
        SurpriseItem(name: "Headache tablets",
                     note: "Altitude headaches are almost universal on arrival — ibuprofen is more effective than paracetamol here",
                     category: .health),
        SurpriseItem(name: "Hydration tablets",
                     note: "Altitude causes faster dehydration — these help you stay on top of it",
                     category: .health),
        SurpriseItem(name: "Extra water (or purification tablets)",
                     note: "Altitude causes faster dehydration — staying ahead of it is the most effective prevention",
                     category: .health),
    ],
    "rainy_city": [
        SurpriseItem(name: "Spare socks",
                     note: "Wet feet are miserable — a dry pair tucked in your bag is pure relief",
                     category: .clothing),
        SurpriseItem(name: "Waterproof pouch",
                     note: "Keeps your phone and wallet genuinely dry in a downpour",
                     category: .essentials),
        SurpriseItem(name: "Packing cubes",
                     note: "Keep damp clothes separated from dry ones — stops everything in your bag smelling by day three",
                     category: .essentials),
        SurpriseItem(name: "Small dry bag for electronics",
                     note: "Laptop, camera, Kindle — one proper drenching can end a trip",
                     category: .electronics),
    ],
    "personal_period": [
        SurpriseItem(name: "Stick-on heat patches",
                     note: "Discreet and hands-free for cramp relief anywhere, anytime",
                     category: .health),
        SurpriseItem(name: "Ibuprofen",
                     note: "More effective than paracetamol for cramping — and harder to find in your preferred brand abroad",
                     category: .health),
        SurpriseItem(name: "Spare underwear (extra set)",
                     note: "Always pack at least one extra set during this time — peace of mind",
                     category: .clothing),
        SurpriseItem(name: "Dark-coloured bottoms",
                     note: "One pair of dark trousers or a dark skirt — a quiet confidence on heavier days",
                     category: .clothing),
    ],
    "personal_medication": [
        SurpriseItem(name: "Prescription copy / letter",
                     note: "Some countries require proof for controlled medications at customs",
                     category: .documents),
        SurpriseItem(name: "Pill organiser",
                     note: "Easier and lighter than carrying full bottles — one for each day",
                     category: .health),
        SurpriseItem(name: "Medication summary card",
                     note: "A card listing your medications, doses, and conditions — invaluable in a medical emergency abroad",
                     category: .documents),
    ],
]

// MARK: - Generation

/// Returns surprise items for the given scene keys, excluding anything already in the packing list.
func computeSurpriseItems(for sceneKeys: [String], existingNames: Set<String>) -> [SurpriseItem] {
    var seen = Set<String>()
    var result: [SurpriseItem] = []
    for key in sceneKeys {
        for item in surpriseItemMap[key] ?? [] {
            let lower = item.name.lowercased()
            guard !seen.contains(lower), !existingNames.contains(lower) else { continue }
            seen.insert(lower)
            result.append(item)
        }
    }
    return result
}
