//
//  SurpriseItemMap.swift
//  Carry
//

import Foundation

// MARK: - SurpriseItem

struct SurpriseItem: Identifiable {
    var id: String { name }
    let name: String
    let note: String
    let category: ItemCategory
}

// MARK: - Scene → surprise item map

let surpriseItemMap: [String: [SurpriseItem]] = [
    "road_trip": [
        SurpriseItem(name: "Instant coffee packets",
                     note: "Long drives get drowsy — just add hot water at any rest stop",
                     category: .essentials),
        SurpriseItem(name: "Emergency blanket",
                     note: "Paper-thin foil blanket that fits in a pocket — invaluable if you break down",
                     category: .essentials),
        SurpriseItem(name: "Wet wipes",
                     note: "Gas station stops, sticky snacks, impromptu cleanups",
                     category: .essentials),
        SurpriseItem(name: "First aid kit",
                     note: "Minor incidents happen far from pharmacies on road trips",
                     category: .health),
        SurpriseItem(name: "Car phone mount",
                     note: "Hands-free navigation is the law in most places — and your co-pilot won't always be awake",
                     category: .essentials),
        SurpriseItem(name: "Jump starter / jump leads",
                     note: "A flat battery on a remote road is a genuine emergency, not just an inconvenience",
                     category: .essentials),
        SurpriseItem(name: "Cash",
                     note: "Toll booths, rural petrol stations, and roadside stalls often don't take cards",
                     category: .documents),
        SurpriseItem(name: "Window sunshade",
                     note: "Parked in the sun, your steering wheel becomes untouchable — costs almost nothing to prevent",
                     category: .essentials),
        SurpriseItem(name: "Offline maps downloaded",
                     note: "Mobile signal disappears exactly when you need navigation most — download before you leave",
                     category: .essentials),
        SurpriseItem(name: "Reusable bags",
                     note: "You will inevitably stop at a supermarket or market — saves scrambling at the checkout",
                     category: .essentials),
    ],
    "long_haul_flight": [
        SurpriseItem(name: "Melatonin",
                     note: "Helps reset your body clock faster at the destination",
                     category: .health),
        SurpriseItem(name: "Breath mints",
                     note: "Cabin air is dry and recycled — your seatmates will appreciate it",
                     category: .essentials),
        SurpriseItem(name: "Moisturiser",
                     note: "Cabin humidity drops to under 20 percent — your skin will beg for this mid-flight",
                     category: .toiletries),
        SurpriseItem(name: "Flight snacks",
                     note: "Airline food timing rarely matches when you're actually hungry",
                     category: .essentials),
        SurpriseItem(name: "Compression socks",
                     note: "DVT is a real risk on long flights — compression socks significantly reduce it",
                     category: .health),
        SurpriseItem(name: "Empty water bottle",
                     note: "Fill after security — saves buying expensive airport water and keeps you hydrated mid-flight",
                     category: .essentials),
        SurpriseItem(name: "Pen",
                     note: "Landing cards, customs forms, hotel addresses — digital boarding passes don't help here",
                     category: .essentials),
        SurpriseItem(name: "Lip balm",
                     note: "Cabin air strips moisture — lips feel it first, hours before you notice anything else",
                     category: .toiletries),
        SurpriseItem(name: "Noise-cancelling earphones",
                     note: "Even cheap ones transform a 12-hour flight — the engine drone wears you down without you realising",
                     category: .electronics),
        SurpriseItem(name: "Neck pillow",
                     note: "Economy sleep is already hard enough — a good travel pillow is worth the carry-on bulk",
                     category: .essentials),
        SurpriseItem(name: "Change of clothes in carry-on",
                     note: "Luggage gets lost more than you'd think — having tomorrow's outfit on you is genuine insurance",
                     category: .clothing),
    ],
    "honeymoon": [
        SurpriseItem(name: "Condoms",
                     note: "Better to have them and not need them",
                     category: .health),
        SurpriseItem(name: "Tea light candles",
                     note: "A handful of small candles can completely transform a hotel room",
                     category: .essentials),
        SurpriseItem(name: "Printed couple photo",
                     note: "A small printed photo makes any hotel room feel personal and yours",
                     category: .essentials),
        SurpriseItem(name: "Bubble bath / bath salts",
                     note: "Most hotel rooms have a bathtub you'll never use otherwise — bring something to make it an event",
                     category: .toiletries),
        SurpriseItem(name: "Portable speaker",
                     note: "Your own playlist beats hotel lobby music — and creates a reason to stay in",
                     category: .electronics),
        SurpriseItem(name: "Nice perfume / cologne",
                     note: "You'll have more occasions to dress up than on a regular holiday",
                     category: .toiletries),
        SurpriseItem(name: "Massage oil",
                     note: "Small, travel-friendly, and creates its own atmosphere — worth the space",
                     category: .toiletries),
        SurpriseItem(name: "Journey journal",
                     note: "Somewhere to write down the small details before they blur together into just 'the honeymoon'",
                     category: .essentials),
        SurpriseItem(name: "Romantic playlist downloaded",
                     note: "Don't leave the mood to Wi-Fi reliability",
                     category: .electronics),
        SurpriseItem(name: "Nice underwear (extra set)",
                     note: "Pack better than you normally would — you'll be glad you did",
                     category: .clothing),
    ],
    "backpacking": [
        SurpriseItem(name: "Laundry detergent sheets",
                     note: "Lightweight and perfect for sink-washing on longer backpacking routes",
                     category: .toiletries),
        SurpriseItem(name: "Carabiner clips",
                     note: "Handy for clipping shoes, bottles, or wet items to your pack exterior",
                     category: .essentials),
        SurpriseItem(name: "Packable daypack",
                     note: "Useful for day trips when you don't want to carry your full backpack",
                     category: .essentials),
        SurpriseItem(name: "Earplugs",
                     note: "Hostel dorms are unpredictable — these are the difference between a good night and a terrible one",
                     category: .essentials),
        SurpriseItem(name: "Money belt",
                     note: "Keeps cash and cards against your body and out of reach when moving between cities",
                     category: .essentials),
        SurpriseItem(name: "Ziplock bags",
                     note: "Waterproofing documents, organising small items, separating wet clothes — endlessly useful",
                     category: .essentials),
        SurpriseItem(name: "Headlamp",
                     note: "Essential for hostel dorm access in the dark without waking eight strangers",
                     category: .essentials),
        SurpriseItem(name: "Portable door lock",
                     note: "Adds a layer of security in hostels and guesthouses where you can't always trust the lock",
                     category: .essentials),
    ],
    "city_break": [
        SurpriseItem(name: "Comfort insoles",
                     note: "City days can hit 20k+ steps — insoles can save your feet by day two",
                     category: .clothing),
        SurpriseItem(name: "Mini anti-theft pouch",
                     note: "Useful in crowded metro/tourist areas where pickpocket risk is higher",
                     category: .essentials),
        SurpriseItem(name: "Refillable water bottle",
                     note: "You walk a lot in city trips; staying hydrated prevents avoidable fatigue",
                     category: .essentials),
        SurpriseItem(name: "Blister plasters",
                     note: "City walking destroys feet — have these before you need them, not after",
                     category: .health),
        SurpriseItem(name: "Collapsible tote bag",
                     note: "You will buy something at a market or deli — saves scrambling for a bag at the checkout",
                     category: .essentials),
        SurpriseItem(name: "Hand cream",
                     note: "A/C, hand sanitiser and constant washing dry hands out fast on city trips",
                     category: .toiletries),
        SurpriseItem(name: "Small combination lock",
                     note: "Useful for securing luggage in hotel lobbies, lockers and train storage racks",
                     category: .essentials),
        SurpriseItem(name: "Offline city map",
                     note: "Data drops at the worst moment — a downloaded map costs nothing and always works",
                     category: .essentials),
    ],
    "tropical": [
        SurpriseItem(name: "Oral rehydration salts",
                     note: "Heat + unfamiliar food can hit hard — these are a quiet lifesaver",
                     category: .health),
        SurpriseItem(name: "Anti-diarrheal tablets",
                     note: "New environments, new bacteria — best to be prepared discreetly",
                     category: .health),
        SurpriseItem(name: "Reef-safe sunscreen",
                     note: "Regular sunscreen damages coral reefs — worth switching in tropical waters",
                     category: .health),
        SurpriseItem(name: "After-sun lotion",
                     note: "Day one is always the burn day — have this ready before you need it",
                     category: .toiletries),
        SurpriseItem(name: "Rash guard",
                     note: "Better sun protection than sunscreen alone, with no reapplying every 90 minutes",
                     category: .clothing),
        SurpriseItem(name: "Waterproof phone case",
                     note: "Snorkelling, pool edges, water taxis — peace of mind for everything around water",
                     category: .essentials),
        SurpriseItem(name: "Antihistamine",
                     note: "Tropical plants, insect bites, unfamiliar foods — allergic reactions spike when everything is new",
                     category: .health),
        SurpriseItem(name: "Light scarf or sarong",
                     note: "Air-conditioned restaurants, temples, beach cover — one piece, five uses",
                     category: .clothing),
        SurpriseItem(name: "Insect repellent wipes",
                     note: "More convenient than spray in a bag — reapply regularly in humid climates",
                     category: .health),
        SurpriseItem(name: "Probiotics",
                     note: "Give your gut a fighting chance in a new food environment — start taking them before you leave",
                     category: .health),
    ],
    "winter": [
        SurpriseItem(name: "Hand warmers",
                     note: "Disposable heat packs — slip into gloves or pockets when it really bites",
                     category: .essentials),
        SurpriseItem(name: "Vaseline / petroleum jelly",
                     note: "Apply to exposed skin before heading out — stops windburn instantly",
                     category: .toiletries),
        SurpriseItem(name: "Wool socks",
                     note: "Cotton socks in freezing temperatures become cold and damp fast — wool insulates even when wet",
                     category: .clothing),
        SurpriseItem(name: "Thermal base layer",
                     note: "The layer closest to your skin matters most — cheap thermals from a supermarket are better than nothing",
                     category: .clothing),
        SurpriseItem(name: "Insulated water bottle",
                     note: "Keeps hot drinks genuinely hot for hours — changes your whole experience outdoors",
                     category: .essentials),
        SurpriseItem(name: "Balaclava or neck gaiter",
                     note: "The face and neck lose heat fastest — often warmer than an extra torso layer",
                     category: .clothing),
        SurpriseItem(name: "Lip sunscreen SPF 30",
                     note: "Snow reflects up to 80 percent of UV — your lips get more sun in winter than you'd expect",
                     category: .toiletries),
        SurpriseItem(name: "Boot dryer inserts",
                     note: "Wet boots overnight become cold boots in the morning — dry them properly",
                     category: .essentials),
        SurpriseItem(name: "Anti-static hairbrush",
                     note: "Cold, dry air makes static worse — natural bristles make a real difference",
                     category: .essentials),
        SurpriseItem(name: "Tissues / handkerchief",
                     note: "Cold air makes noses run constantly — running out of tissues in the cold is genuinely unpleasant",
                     category: .essentials),
    ],
    "hiking": [
        SurpriseItem(name: "Blister plasters",
                     note: "New boots + long trails = blisters — these prevent the worst",
                     category: .health),
        SurpriseItem(name: "Electrolyte tablets",
                     note: "Water alone doesn't replace what you sweat out on a long hike",
                     category: .health),
        SurpriseItem(name: "Emergency whistle",
                     note: "Three blasts is the universal distress signal — and it weighs almost nothing",
                     category: .essentials),
        SurpriseItem(name: "Headtorch + spare batteries",
                     note: "If a hike runs longer than planned, you'll be very glad this is in your pack",
                     category: .essentials),
        SurpriseItem(name: "Lightweight rain poncho",
                     note: "Weather changes fast on trails — a 200g poncho is better insurance than a heavy jacket",
                     category: .clothing),
        SurpriseItem(name: "Waterproof dry bag",
                     note: "For when a stream crossing goes slightly wrong — protects everything that matters",
                     category: .essentials),
        SurpriseItem(name: "Trail snacks / energy bars",
                     note: "Always bring more food than you think you need — you'll be burning more than you expect",
                     category: .essentials),
        SurpriseItem(name: "Sun hat with brim",
                     note: "Hours on exposed ridges with no shade — your face and neck will thank you",
                     category: .clothing),
        SurpriseItem(name: "Compact microfibre towel",
                     note: "For river crossings, unexpected rain, or just sweating heavily on a long ascent",
                     category: .essentials),
        SurpriseItem(name: "Duct tape (small roll)",
                     note: "Fixes a broken boot sole, a torn strap, or a blister spot — worth the 30g",
                     category: .essentials),
    ],
    "cruise": [
        SurpriseItem(name: "Magnetic hooks",
                     note: "Cruise cabin walls are magnetic — hang bags and coats with no damage",
                     category: .essentials),
        SurpriseItem(name: "Acupressure wristbands",
                     note: "Drug-free and surprisingly effective for seasickness — wear from day one",
                     category: .health),
        SurpriseItem(name: "Power strip / multi-socket",
                     note: "Cruise cabins famously have very few sockets — one strip solves everyone's charging",
                     category: .electronics),
        SurpriseItem(name: "Collapsible hanging organiser",
                     note: "Cabin storage is cleverly minimal — over-door pouches multiply your space significantly",
                     category: .essentials),
        SurpriseItem(name: "Lanyard for cruise card",
                     note: "You'll tap it at every door, bar, and restaurant — a lanyard keeps it accessible without digging",
                     category: .essentials),
        SurpriseItem(name: "Seasickness tablets",
                     note: "Wristbands help but when seas get rough, proper medication is what you'll actually want",
                     category: .health),
        SurpriseItem(name: "Portable fan",
                     note: "Cabins can get warm, especially in tropical ports — a small USB fan is a real sleep improvement",
                     category: .essentials),
        SurpriseItem(name: "Formal outfit cover",
                     note: "Formal nights happen — a dedicated garment bag keeps your one good outfit unwrinkled",
                     category: .clothing),
        SurpriseItem(name: "Travel plug adapter",
                     note: "Ships use a mix of socket types depending on registry — check before boarding",
                     category: .electronics),
        SurpriseItem(name: "Deck shoes",
                     note: "Wet pool decks and formal dining in the same day require footwear that can do both",
                     category: .clothing),
    ],
    "business": [
        SurpriseItem(name: "Spare pens × 2",
                     note: "Your pen always runs out the moment you need to sign something important",
                     category: .essentials),
        SurpriseItem(name: "Phone stand",
                     note: "Frees your hands during video calls from hotel rooms",
                     category: .electronics),
        SurpriseItem(name: "Business cards",
                     note: "Your phone is for their contact. Your card is for theirs — some markets still expect them",
                     category: .essentials),
        SurpriseItem(name: "Portable battery pack",
                     note: "Between airports, taxis, and dinners your phone will hit 3 percent at exactly the wrong moment",
                     category: .electronics),
        SurpriseItem(name: "Wrinkle-release spray",
                     note: "Meeting clothes out of a suitcase always need a refresh — no iron required",
                     category: .toiletries),
        SurpriseItem(name: "Dress socks (spare pair)",
                     note: "Coffee, puddles, hotel breakfasts — formal wardrobe disasters always involve socks",
                     category: .clothing),
        SurpriseItem(name: "Compact umbrella",
                     note: "Arriving at a client's office soaked is not the impression you want to make",
                     category: .essentials),
        SurpriseItem(name: "Noise-cancelling earphones",
                     note: "Back-to-back flights, open lobbies, and conference calls — you'll use them constantly",
                     category: .electronics),
        SurpriseItem(name: "Bluetooth presenter / clicker",
                     note: "For slide-based presentations away from your own keyboard — smooth and professional",
                     category: .electronics),
        SurpriseItem(name: "Stain remover pen",
                     note: "One coffee incident before a meeting — this pen has saved careers",
                     category: .essentials),
    ],
    "kids": [
        SurpriseItem(name: "Extra outfit in carry-on",
                     note: "For spills at 30,000 feet — before you can access your checked luggage",
                     category: .clothing),
        SurpriseItem(name: "Familiar snacks from home",
                     note: "Picky eaters + unfamiliar food = avoidable stress — come prepared",
                     category: .essentials),
        SurpriseItem(name: "Child's own small backpack",
                     note: "Their bag to carry builds independence — and means you're not carrying absolutely everything",
                     category: .essentials),
        SurpriseItem(name: "Reusable wet bag",
                     note: "For wet swimsuits, soiled clothes, or snack wrappers — contains the chaos neatly",
                     category: .essentials),
        SurpriseItem(name: "Night light",
                     note: "New rooms are dark in unfamiliar ways — a simple plug-in night light prevents middle-of-the-night panic",
                     category: .essentials),
        SurpriseItem(name: "Children's pain/fever relief",
                     note: "Fever at 11pm in an unfamiliar country is when you want this to already be in your bag",
                     category: .health),
        SurpriseItem(name: "Sticker book or activity pad",
                     note: "For the unavoidable waiting — restaurants, airports, long car journeys",
                     category: .essentials),
        SurpriseItem(name: "Portable white noise app or device",
                     note: "Unfamiliar hotel rooms are hard for small sleepers — familiar sounds make an enormous difference",
                     category: .essentials),
        SurpriseItem(name: "Child's favourite soft toy",
                     note: "Sleep away from home is genuinely harder for small children — familiar comfort matters",
                     category: .essentials),
        SurpriseItem(name: "Swim nappies",
                     note: "Even if rarely needed, the one time you need them and don't have them is memorable for all the wrong reasons",
                     category: .essentials),
    ],
    "high_altitude": [
        SurpriseItem(name: "Coca tea bags",
                     note: "Traditional remedy for altitude sickness — widely available and effective in the Andes",
                     category: .health),
        SurpriseItem(name: "Hydration tablets",
                     note: "Altitude causes faster dehydration — these help you stay on top of it",
                     category: .health),
        SurpriseItem(name: "Acetazolamide (Diamox)",
                     note: "The prescription medication for altitude sickness prevention — ask your GP at least a week before you go",
                     category: .health),
        SurpriseItem(name: "SPF 50+ sunscreen",
                     note: "UV radiation increases with altitude — at 4,000m you burn in a fraction of sea-level time",
                     category: .toiletries),
        SurpriseItem(name: "Lip balm SPF 30",
                     note: "Wind, altitude, and UV all attack exposed lips — protect them before they crack, not after",
                     category: .toiletries),
        SurpriseItem(name: "Lightweight down jacket",
                     note: "Temperatures drop fast after sunset at altitude even in summer — always have one layer extra",
                     category: .clothing),
        SurpriseItem(name: "Headache tablets",
                     note: "Altitude headaches are almost universal on arrival — ibuprofen is more effective than paracetamol here",
                     category: .health),
        SurpriseItem(name: "Pulse oximeter",
                     note: "Small and cheap — monitoring blood oxygen shows how well you're actually acclimatising",
                     category: .health),
        SurpriseItem(name: "Extra water (or purification tablets)",
                     note: "Altitude causes faster dehydration — staying ahead of it is the most effective prevention",
                     category: .health),
    ],
    "rainy_city": [
        SurpriseItem(name: "Waterproof pouch",
                     note: "Keeps your phone and wallet genuinely dry in a downpour",
                     category: .essentials),
        SurpriseItem(name: "Spare socks",
                     note: "Wet feet are miserable — a dry pair tucked in your bag is pure relief",
                     category: .clothing),
        SurpriseItem(name: "Compact umbrella",
                     note: "Obvious — but it's the first thing you leave behind, every time. Check it's in the bag",
                     category: .essentials),
        SurpriseItem(name: "Waterproof trainers / shoes",
                     note: "Regular shoes absorb water fast and take days to dry — waterproof ones change everything in a wet city",
                     category: .clothing),
        SurpriseItem(name: "Quick-dry travel trousers",
                     note: "Cotton trousers take a day to dry when soaked — synthetic or wool alternatives dry by morning",
                     category: .clothing),
        SurpriseItem(name: "Backpack rain cover",
                     note: "Most bags are not remotely waterproof — a cover weighs 100g and keeps everything inside dry",
                     category: .essentials),
        SurpriseItem(name: "Packing cubes",
                     note: "Keep damp clothes separated from dry ones — stops everything in your bag smelling by day three",
                     category: .essentials),
        SurpriseItem(name: "Small dry bag for electronics",
                     note: "Laptop, camera, Kindle — one proper drenching can end a trip",
                     category: .electronics),
        SurpriseItem(name: "Anti-humidity hair product",
                     note: "Humidity doubles frizz and flatness — a small anti-humidity product is worth the space in a wet city",
                     category: .toiletries),
    ],
    "personal_period": [
        SurpriseItem(name: "Stick-on heat patches",
                     note: "Discreet and hands-free for cramp relief anywhere, anytime",
                     category: .health),
        SurpriseItem(name: "Spare underwear (extra set)",
                     note: "Always pack at least one extra set during this time — peace of mind",
                     category: .clothing),
        SurpriseItem(name: "Dark-coloured bottoms",
                     note: "One pair of dark trousers or a dark skirt — a quiet confidence on heavier days",
                     category: .clothing),
        SurpriseItem(name: "Ibuprofen",
                     note: "More effective than paracetamol for cramping — and harder to find in your preferred brand abroad",
                     category: .health),
        SurpriseItem(name: "Your own supply of preferred products",
                     note: "Brands and absorbencies vary wildly by country — don't rely on finding your usual",
                     category: .health),
        SurpriseItem(name: "Dedicated small pouch for supplies",
                     note: "Discreet, organised, fits in any day bag — dedicated storage removes the scramble",
                     category: .essentials),
        SurpriseItem(name: "Digestive support (ginger or probiotics)",
                     note: "Bloating and digestive changes are common during this time — help your gut along",
                     category: .health),
        SurpriseItem(name: "Lightweight hot water bottle",
                     note: "Even travel-size relieves cramps better than patches on difficult days",
                     category: .health),
    ],
    "personal_coffee": [
        SurpriseItem(name: "Travel mug",
                     note: "Keeps coffee hot for hours — works equally well for cold brew",
                     category: .essentials),
        SurpriseItem(name: "Collapsible coffee dripper",
                     note: "Hotel kettle + your own grounds = decent coffee anywhere",
                     category: .essentials),
        SurpriseItem(name: "Ground coffee for the trip",
                     note: "Hotel in-room coffee is almost universally bad — your own grounds transform the morning routine",
                     category: .essentials),
        SurpriseItem(name: "AeroPress or portable espresso maker",
                     note: "Battery-free, indestructible, and makes genuinely excellent coffee anywhere there's hot water",
                     category: .essentials),
        SurpriseItem(name: "Reusable filter papers",
                     note: "Many pour-over setups use filters you run out of mid-trip — bring extras or a reusable one",
                     category: .essentials),
        SurpriseItem(name: "Insulated flask for cold brew",
                     note: "Make cold brew overnight in the hotel fridge — works with any container and a filter",
                     category: .essentials),
        SurpriseItem(name: "Small hand grinder",
                     note: "If you care this much, you already know why freshly ground coffee is worth the extra weight",
                     category: .essentials),
    ],
    "personal_tea": [
        SurpriseItem(name: "Travel mug",
                     note: "Keeps tea hot for hours — hotel kettles are everywhere",
                     category: .essentials),
        SurpriseItem(name: "Tea variety pack",
                     note: "Bring your favourites from home — hotel tea bags rarely satisfy",
                     category: .essentials),
        SurpriseItem(name: "Portable electric travel kettle",
                     note: "For rooms without a kettle — or where the hotel kettle cannot be trusted to be clean",
                     category: .essentials),
        SurpriseItem(name: "Tea infuser / loose leaf strainer",
                     note: "Most hotels only have bags — this lets you bring what you actually enjoy",
                     category: .essentials),
        SurpriseItem(name: "Thermos flask",
                     note: "Brew once in the morning, drink hot tea for hours without finding a cafe",
                     category: .essentials),
        SurpriseItem(name: "Small honey packets",
                     note: "Single-serve honey sticks travel perfectly and make even average tea genuinely comforting",
                     category: .essentials),
        SurpriseItem(name: "Ginger tea for travel",
                     note: "Ginger tea genuinely helps with motion sickness and upset stomachs — worth a few extra bags",
                     category: .health),
    ],
    "personal_medication": [
        SurpriseItem(name: "Prescription copy / letter",
                     note: "Some countries require proof for controlled medications at customs",
                     category: .documents),
        SurpriseItem(name: "Pill organiser",
                     note: "Easier and lighter than carrying full bottles — one for each day",
                     category: .health),
        SurpriseItem(name: "Medication summary card",
                     note: "A card listing your medications, doses, and conditions — invaluable in a medical emergency abroad",
                     category: .documents),
        SurpriseItem(name: "Extra 2-week supply beyond trip length",
                     note: "Flight delays, extensions, lost luggage — always carry more medication than you think you need",
                     category: .health),
        SurpriseItem(name: "Separate insurance / medical card",
                     note: "Keep it in your day bag, not buried in your luggage — accessible when you actually need it",
                     category: .documents),
        SurpriseItem(name: "Allergy information (translated)",
                     note: "If you have serious drug or food allergies, a note in the local language can prevent emergencies",
                     category: .documents),
        SurpriseItem(name: "Medication cooling case (if needed)",
                     note: "For medications requiring refrigeration — travel insulin cases with ice packs exist for exactly this",
                     category: .health),
    ],
]

// MARK: - Generation

/// Returns surprise items for the given scene keys, excluding anything already in the packing list.
func computeSurpriseItems(for sceneKeys: [String], existingNames: Set<String>) -> [SurpriseItem] {
    var seen = Set<String>()
    var result: [SurpriseItem] = []
    for key in sceneKeys {
        for item in surpriseItemMap[key] ?? [] {
            let lower = item.name.lowercased()
            guard !seen.contains(lower), !existingNames.contains(lower) else { continue }
            seen.insert(lower)
            result.append(item)
        }
    }
    return result
}
